name: disease-classification
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - pillow>=8.3.0
  - tqdm>=4.62.0
  - wandb>=0.12.0
  - yacs>=0.1.8
  - pandas>=1.3.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - opencv>=4.5.0
  - pip>=21.0.0
  - pip:
    - grad-cam>=1.4.0
    - albumentations>=1.1.0
    - timm>=0.4.12
    - tensorboard>=2.7.0
    - tensorboardX>=2.4
    - thop>=0.0.31
    - pyyaml>=5.4.0
    - pathlib2>=2.3.0
    - future>=0.18.0
    - six>=1.16.0
    - requests>=2.25.0
    - urllib3>=1.26.0
    - certifi>=2021.5.30
    - chardet>=4.0.0
    - idna>=2.10
    - click>=8.0.0
    - packaging>=21.0
    - pyparsing>=2.4.7
    - kiwisolver>=1.3.1
    - cycler>=0.10.0
    - python-dateutil>=2.8.2
    - decorator>=5.0.9
    - networkx>=2.6.0
    - imageio>=2.9.0
